In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
digits = datasets.load_digits()

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
from sklearn import svm

In [11]:
classifier = svm.SVC(gamma = 0.001, C=100)

In [12]:
classifier

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0, degree=3,
  gamma=0.001, kernel='rbf', max_iter=-1, probability=False,
  random_state=None, shrinking=True, tol=0.001, verbose=False)

In [13]:
classifier.fit(digits.data[:-1], digits.target[:-1])

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0, degree=3,
  gamma=0.001, kernel='rbf', max_iter=-1, probability=False,
  random_state=None, shrinking=True, tol=0.001, verbose=False)

In [14]:
classifier.predict(digits.data[-1])

array([8])

In [15]:
classifier_iris = svm.SVC()

In [16]:
X, y = iris.data, iris.target

In [17]:
classifier_iris.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0, degree=3, gamma=0.0,
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [18]:
import pickle

In [20]:
s = pickle.dumps(classifier_iris)

In [21]:
classifier_iris_2 = pickle.loads(s)

In [22]:
classifier_iris_2.predict(X[0:1])

array([0])

In [23]:
y[0]

0

In [25]:
import numpy as np
from sklearn import random_projection

In [29]:
rng = np.random.RandomState(0)

In [30]:
X = rng.rand(10,2000)

In [33]:
X = np.array(X, dtype='float32')

In [34]:
X.dtype

dtype('float32')

In [35]:
transformer = random_projection.GaussianRandomProjection()

In [37]:
X_new = transformer.fit_transform(X)

In [38]:
X_new.dtype

dtype('float64')

In [40]:
from sklearn.svm import SVC

In [41]:
classifier_3 = SVC()